version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# Commenting out formats section as the PDF and EPUB builds are failing
# due to unsupported Unicode characters in LaTeX (emoji characters)
# formats:
#   - pdf
#   - epub
